export const DISCORD_ID = "855130539048960030";
export const USERNAME = "ultirequiem";
export const COUNTRY = "Peru";
export const NAME = "Eliaz";
export const FULL_NAME = `${NAME} Bobadilla`;
export const POSITION = "Software Engineer";
export const CURRENT_YEAR = new Date().getFullYear();
export const PFP = "https://avatars.githubusercontent.com/u/71897736?v=4";
export const GITHUB = `https://github.com/${USERNAME}`;
export const TWITTER = `https://twitter.com/${USERNAME}`;
export const LINKEDIN = `https://www.linkedin.com/in/${USERNAME}`;
export const EMAIL = "eliaz.bobadilladev@gmail.com";
export const TELEPHONE_NUMBER = "+51 923-531-893";
